import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import type { MergerParams } from './index.js'
import { collectBuiltinFiltered, sortedObjectNames, resolveImports } from './index.js'

export function pythonMerge(params: MergerParams): string[] {
  const { workspace, depGraph, scc, order, generatedCodeMap, outputDir } = params
  const ext = '.py'
  const files: string[] = []
  const compToBaseName = new Map<number, string>()
  const compToPath = new Map<number, string>()

  for (const compStr of order) {
    const comp = Number(compStr)
    const ids = collectBuiltinFiltered(scc, comp)
    if (ids.length === 0) continue

    const baseName = sortedObjectNames(workspace, ids).join('And')
    compToBaseName.set(comp, baseName)

    if (ids.length === 1) {
      compToPath.set(comp, resolve(outputDir, `${baseName}${ext}`))
    } else {
      compToPath.set(comp, resolve(outputDir, baseName, `__init__${ext}`))
    }
  }

  for (const compStr of order) {
    const comp = Number(compStr)
    const filePath = compToPath.get(comp)
    if (!filePath) continue

    const ids = collectBuiltinFiltered(scc, comp)

    const codeParts: string[] = []
    for (const id of ids) {
      const code = generatedCodeMap.get(id)
      if (code) {
        codeParts.push(code)
      } else {
        const decl = workspace.getObject(id)
        codeParts.push(`# TODO: generate ${decl?.name ?? id} — LLM call failed`)
      }
    }

    const importMap = resolveImports(
      workspace,
      depGraph,
      scc,
      ids,
      comp,
      compToBaseName,
      outputDir,
      dirname(filePath)
    )

    const importLines: string[] = []
    for (const [importPath, names] of importMap) {
      let modPath: string
      if (importPath.startsWith('./')) {
        modPath = '.' + importPath.slice(2).replace(/\//g, '.')
      } else if (importPath.startsWith('../')) {
        modPath = '..' + importPath.slice(3).replace(/\//g, '.')
      } else {
        modPath = importPath.replace(/\//g, '.')
      }
      importLines.push(`from ${modPath} import ${[...names].sort().join(', ')}`)
    }

    const content =
      '# Auto-generated by Synthia\n' +
      (importLines.length > 0 ? importLines.join('\n') + '\n\n' : '') +
      codeParts.join('\n\n') +
      '\n'

    mkdirSync(dirname(filePath), { recursive: true })
    writeFileSync(filePath, content, 'utf-8')
    files.push(filePath)
  }

  return files
}
